### ISSUE TITLE
System.BadImageFormatException

### ISSUE THREAD

**Issue by MPasadu** [george-polevoy/JumboExcel#3]
Hey,
really nice library. Unfortunately there is an exception thrown on most tests in DemoTests:

> Message: System.BadImageFormatException : An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)

All the performance tests throw this exception. I tried setting everything to x86 or x64, updating NUnit to the latest v3 and also NUnitTestAdapter3 but still the same errors. Also tried deleting the externel reference to DocumentFormat.OpenXml.dll and installed the latest version with nuget.

Any idea?

**Comment by george-polevoy** [comment]
Closing as NET 4 is not supported anymore.
